### ISSUE TITLE
"read /Users/username: is a directory" when defaulting to SSH SOCKET

### ISSUE THREAD

**Issue by Zhann** [hypersleep/easyssh#17]
Using the example shown in https://github.com/hypersleep/easyssh/blob/master/example/run.go but leaving out the Key parameter on line 15 (ensuring it tries to contact the agent SOCKET), I get:

```
panic: Can't run remote command: read /Users/steven: is a directory

goroutine 1 [running]:
panic(0x1f5680, 0xc82000a940)
        /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
gitlab.openminds.be/openminds/gom-awesome/modules/whereis.Whereis()
        /Users/steven/Code/Zhann/go/src/gitlab.openminds.be/openminds/gom-awesome/modules/whereis/whereis.go:17 +0x1a3
main.main()
        /Users/steven/Code/Zhann/go/src/gitlab.openminds.be/openminds/gom-awesome/gom.go:11 +0xd1
```

I can't seem to wrap my head around why. It's not possible for me to set the Key parameter, because then I bump into https://github.com/hypersleep/easyssh/issues/3, I'm hoping to work around this by using the agent SOCKET.

**Comment by Zhann** [comment]
Never mind, I was using and old version of this library: `"gopkg.in/hypersleep/easyssh.v0"` (as found in https://github.com/hypersleep/easyssh/blob/master/example/run.go).

Fixed now!
